spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springbootshiro?characterEncoding=utf8&allowMultiQueries=true&useSSL=false
    username: root
    password: root9898008
    driver-class-name: com.mysql.cj.jdbc.Driver
  resources:
    add-mappings: true
    cache:
      period: 3600
    chain:
      cache: true
      enabled: true
      compressed: true
      html-application-cache: true
    static-locations: classpath:/static/

#redis
redis:
  host: 127.0.0.1
  port: 6379
  timeout: 3
  password:
  poolMaxTotal: 1000
  poolMaxIdle: 500
  poolMaxWait: 3

