spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springbootshiro?characterEncoding=utf8&allowMultiQueries=true&useSSL=false
    username: root
    password: root9898008
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    single: 127.0.0.1:6379
    jedis:
      pool:
        max-idle: 8
        max-active: 8
        max-wait: 3000
    timeout: 3000
    password:
  resources:
    add-mappings: true
    cache:
      period: 3600
    chain:
      cache: true
      enabled: true
      compressed: true
      html-application-cache: true
    static-locations: classpath:/static/

